apiVersion: apps/v1
kind: Deployment
metadata:
  name: member
spec:
  replicas: 2
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
    spec:
      containers:
        - name: member
          image: ddung1203/demo:member
          imagePullPolicy: Always
          ports:
            - containerPort: 9560