apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
        - name: movie
          image: ddung1203/demo:movie
          imagePullPolicy: Always
          ports:
            - containerPort: 9009