server:
  port : 8080


spring:
  config:
    import: "optional:configserver:http://localhost:8888"

  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: http://localhost:9560/
          predicates:
            - Path=/member/**
        - id: movie-service
          uri: http://localhost:9009/
          predicates:
            - Path=/movie/**

#spring:
#  cloud:
#    gateway:
#      default-filters:
#        args:
#          baseMessage: Spring Cloud Gateway GlobalFilter
#          preLogger: true
#          postLogger: true
#      routes:
#        - id: member-service
##          uri: lb://member
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/member/**
#          filters:
#            - name: MemberFilter
#              args:
#                baseMessage: Spring Cloud Gateway MemberFilter
#                preLogger: true
#                postLogger: true
#        - id: movies-service
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/movies/**
#          filters:
#            - name: MemberFilter
#              args:
#                baseMessage: Spring Cloud Gateway MemberFilter
#                preLogger: true
#                postLogger: true