server:
  port : 8080

spring:

  zipkin:
    enabled: false
  application:
    name: apigateway-service
    instance_id:

  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
    gateway:
      routes:
        - id: member-service
          uri: member-app-deployment.default:9560/
#          uri: http://localhost:9560/
          predicates:
            - Path=/member/**
          filters:
            - RewritePath=/movie/?(?<segment>.*), /$\{segment}
#            - AuthorizationFilter

        - id: movie-service
          uri: rcmn-app-deployment.default:9009/
          predicates:
            - Path=/movie/**
          filters:
            - RewritePath=/movie/?(?<segment>.*), /$\{segment}
            - AuthorizationFilter
eureka:
  client:
    fetch-registry: false # 유레카 클라이언트 활성화
    register-with-eureka: false # 유레카 클라이언트 활성화
    service-url:
      defaultZone: http://localhost:8761/eureka # 유레카 클라이언트로 등록
