server:
  port: 9009

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  application:
    name: RECOMMEND-SERVICE
