apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.app_label }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_label }}
    spec:
      containers:
        - name: {{ .Values.app_label }}
          image: {{ .Values.app_image }}
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: myweb-svc-lb
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.app_label }}
  ports:
    - port: 80
      targetPort: 3000